name: Shell CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check file exists
        run: |
          if [ -f test.txt ]; then
            echo "File exists"
          else
            echo "File missing"
            exit 1
          fi

      - name: Validate content
        run: |
          if grep -q "Hello CI" test.txt; then
            echo "Content valid"
          else
            echo "Content invalid"
            exit 1
          fi
